Clarified Slices documentation
TNG/ArchUnit pull request #1366
Opened 2024-10-19 08:50 UTC by mipo256

The slices documentation does not mention a very important aspect, that is that, technically, Slices do not represent a given set of packages, although the example shows that.

2024-10-19 19:02 UTC, andrzejsydor approved these changes

2025-01-17 08:34 UTC, hankem commented
Thanks for your contribution! 🙏 Sorry that this PR has been overlooked for so long... 🙈

Could you please sign-off your commit according to the [DCO](https://github.com/TNG/ArchUnit/blob/main/DCO), cf. [Contributing guideline](https://github.com/TNG/ArchUnit/blob/main/CONTRIBUTING.md)?

2025-01-17 09:03 UTC, mipo256 commented
Hey @hankem, yeah, sure, I've signed off the commit

2025-01-17 12:44 UTC, hankem commented on archunit/src/main/java/com/tngtech/archunit/library/dependencies/Slice.java
>   * housing all the classes from the {@code customer} package and so on.
As the rest of the JavaDoc still refers to the example in the `<code>` block:

How about moving your suggestion to a new paragraph at the end?
With tiny modifications, I'd suggest:
```suggestion
 * The top level packages under 'myapp' could be considered slices according to different domain aspects.<br>
 * Thus there could be a slice 'Order' housing all the classes from the {@code order} package, a slice 'Customer'
 * housing all the classes from the {@code customer} package and so on.
  * <p>
 * Note that a {@link Slice} does not necessarily represent a set of subpackages inside the given root package.
 * The example above is just a common use case, but {@link Slice slice} can technically represent any set
 * of {@link JavaClass JavaClasses}.
 * </p>
```

2025-01-17 12:49 UTC, mipo256 commented on archunit/src/main/java/com/tngtech/archunit/library/dependencies/Slice.java
>   * housing all the classes from the {@code customer} package and so on.
Sounds good, I agree

2025-01-17 13:04 UTC, hankem commented on archunit/src/main/java/com/tngtech/archunit/library/dependencies/Slice.java
>   * housing all the classes from the {@code customer} package and so on.
Thanks for the update! Could you still move the new paragraph to the end of the JavaDoc? (And should we close it with `</p>`?)

2025-01-17 13:07 UTC, hankem commented
Oh, and one more request (sorry! 🙈): Could you please rebase your branch onto the current `main` branch?
GitHub might not let me merge it while this branch is out-of-date with the base branch.

2025-01-17 13:18 UTC, mipo256 commented on archunit/src/main/java/com/tngtech/archunit/library/dependencies/Slice.java
>   * housing all the classes from the {@code customer} package and so on.
Yeah, we should, sorry, missed that :)

2025-01-19 11:05 UTC, hankem commented on archunit/src/main/java/com/tngtech/archunit/library/dependencies/Slice.java
>   * housing all the classes from the {@code customer} package and so on.
FYI: I've prepared the rebased commit with the tiny adaption as we agreed on branch `PR1366-mipo256` (I couldn't update yours). Maybe we'll find a way to include it in the upcoming release?

2025-01-19 11:08 UTC, mipo256 commented on archunit/src/main/java/com/tngtech/archunit/library/dependencies/Slice.java
>   * housing all the classes from the {@code customer} package and so on.
Hey @hankem!
Yeah, I will provide the necessary changes very shortly

2025-01-19 11:34 UTC, mipo256 commented on archunit/src/main/java/com/tngtech/archunit/library/dependencies/Slice.java
>   * housing all the classes from the {@code customer} package and so on.
Done.
Anything else @hankem ?

2025-01-19 12:29 UTC, hankem approved these changes

2025-01-19 12:32 UTC, hankem commented on archunit/src/main/java/com/tngtech/archunit/library/dependencies/Slice.java
>   * housing all the classes from the {@code customer} package and so on.
Thanks for your effort on a Sunday! 
My last request (cf. https://github.com/TNG/ArchUnit/pull/1366#issuecomment-2598332165) is to rebase your branch on the current `main` branch on this https://github.com/TNG/ArchUnit/ repository to make the PR mergable.

2025-01-19 12:46 UTC, mipo256 commented
oops, sorry, I'll reopen it

2025-01-19 14:26 UTC, codecholeric requested changes

2025-01-19 14:26 UTC, codecholeric commented on archunit/src/main/java/com/tngtech/archunit/library/dependencies/Slice.java
> + * Note that a {@link Slice} does not necessarily represent a subpackage inside>
This looks a little odd now, no? 🤔 Why is it cut off like this?

2025-01-20 06:58 UTC, hankem commented on archunit/src/main/java/com/tngtech/archunit/library/dependencies/Slice.java
> + * Note that a {@link Slice} does not necessarily represent a subpackage inside>
Oops, the line somehow got cut off at 80 characters. 🙈

@mipo256 , you could still restore my suggestion using
```
git remote add TNG https://github.com/TNG/ArchUnit.git
git fetch TNG
git reset TNG/PR1366-mipo256
```

2025-01-20 09:36 UTC, mipo256 commented on archunit/src/main/java/com/tngtech/archunit/library/dependencies/Slice.java
> + * Note that a {@link Slice} does not necessarily represent a subpackage inside>
Done @hankem :)

2025-01-20 09:38 UTC, mipo256 commented
I applied the suggestion, and the commit is signed off, it is strange that the DCO is red...

2025-01-20 19:39 UTC, hankem approved these changes
Maybe the DCO check was confused because of the discrepancy of the author (you), commiter (me), and sign-off (you, with another name and email address)?
But I think that it should be fine; I found a setting to set the check to pass.

2025-01-23 07:37 UTC, hankem commented
@mipo256, could you [allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests) (or rebase to `master` once again)?

GitHub doesn't let me merge this PR because
![it is out-of-date with the base branch](https://github.com/user-attachments/assets/1b5a0f33-6230-420a-808c-21bba0b78229)

2025-01-23 10:32 UTC, mipo256 commented
Rebased

2025-01-25 10:16 UTC, merged