Track method references
TNG/ArchUnit pull request #649
Opened 2021-08-13 13:36 UTC by KorSin

2021-08-20 17:58 UTC, codecholeric commented
Thanks a lot for the initiative :smiley: Let's discuss this a little more via Zoom, since I think there is a lot that needs to be figured out with regards to the domain model.
I'm strongly convinced that these things are no "calls" at all, because I can hold a method reference forever without ever invoking the method it refers to...

2021-12-19 16:06 UTC, codecholeric requested changes
Nice work, thanks a lot for the hard work! :smile: Since this is a quite complex topic I of course still have some comments and nitpicks :joy: 
And I have also a bigger thing we could consider: If we want to use this now to eliminate these synthetic intermediate methods for lambda calls :thinking: 
Because with your new additions, as you have also mentioned, you will now pick up those dynamic invocations to these synthetic static methods created for lambda calls (e.g. `lambda$someMethod$0`, etc.). I don't think we want those (because they are also not "method references" in my opinion). However, we at the moment also have these cryptic calls originating from methods like `lambda$someMethod$0`, so we could actually use this information to reconstruct a lambda call from one method to another method by combining the dynamic invocation to the synthetic method and the call from the synthetic method to the target method.
Anyway, I think it makes sense to pair program on this, be it the review comments or that further idea, so we don't run too many review cycles :slightly_smiling_face: In any case I played around a little and picking up method and constructor references seems to work nicely now :+1:

2021-12-22 16:17 UTC, KorSin commented on archunit/src/main/java/com/tngtech/archunit/core/domain/JavaCodeUnit.java
> +        return ImmutableSet.<JavaReference<?>>builder()
To be consistent with other methods in this class, it is not used.

2022-01-02 17:55 UTC, codecholeric approved these changes
Looks good to me, thanks for all the hard work, really appreciated :smile:

2022-01-02 17:56 UTC, codecholeric commented
We still need to rebase once #755 has been merged

2022-01-13 19:17 UTC, merged